plugins {
    id 'java-library'
}

dependencies {
    api "org.slf4j:slf4j-api:${slf4jVersion}"
    api "org.yaml:snakeyaml:${snakeyamlVersion}"
    api "com.google.code.gson:gson:${gsonVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
    testRuntimeOnly "org.slf4j:slf4j-simple:${slf4jVersion}"
}

jar {
    archiveBaseName.set('antivpn-core')
}
